### ISSUE TITLE
Create a slack team for CISSUSL

### ISSUE THREAD

**Issue by dilumn** [CISSUSL/news-app-iOS#5]
This is not something related with `news-app-iOS`,

Shall we create a Slack team which is parallel to the `CISSUSL` github org?

**Comment by isuruAb** [comment]
@dilumn  yes sure. I will create one today.
We already have a gitter channel https://gitter.im/CIS-SUSL/Lobby

**Comment by dilumn** [comment]
I integrated `Github` with the slack channel. So every event will be notified to a slack channel.

@isuruAb it's good have the developers who are contributing / willing to contribute in the slack team. So they will see what's happening in the org. But tell them to install slack application into their laptops

**Comment by isuruAb** [comment]
@dilumn this can be closed ?
